In [ ]:

1. Scenario: A company wants to analyze the sales performance of its products in different regions. They have collected the following data:
   Region A: [10, 15, 12, 8, 14]
   Region B: [18, 20, 16, 22, 25]
   Calculate the mean sales for each region.


In [2]:
import numpy as np
A= [10, 15, 12, 8, 14]
B= [18, 20, 16, 22, 25]
print(f"mean sales for region A is {np.mean(A)}")
print(f"mean sales for region B is {np.mean(B)}")

mean sales for region A is 11.8
mean sales for region B is 20.2


In [ ]:
2. Scenario: A survey is conducted to measure customer satisfaction on a scale of 1 to 5. The data collected is as follows:
   [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
   Calculate the mode of the survey responses.

In [4]:
A=[4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
import statistics as stats
stats.mode(A)

4

In [ ]:
3. Scenario: A company wants to compare the salaries of two departments. The salary data for Department A and Department B are as follows:
   Department A: [5000, 6000, 5500, 7000]
   Department B: [4500, 5500, 5800, 6000, 5200]
   Calculate the median salary for each department.


In [6]:
A= [5000, 6000, 5500, 7000]
B= [4500, 5500, 5800, 6000, 5200]
print(np.median(A))
np.median(B)

5750.0


5500.0

In [ ]:
4. Scenario: A data analyst wants to determine the variability in the daily stock prices of a company. The data collected is as follows:
   [25.5, 24.8, 26.1, 25.3, 24.9]
   Calculate the range of the stock prices.


In [22]:
A=[25.5, 24.8, 26.1, 25.3, 24.9]
A.sort()
q1=np.percentile(A,25)
q3=np.percentile(A,75)
print((q3-q1)*2)

1.2000000000000028


In [ ]:
5. Scenario: A study is conducted to compare the performance of two different teaching methods. The test scores of the students in each group are as follows:
   Group A: [85, 90, 92, 88, 91]
   Group B: [82, 88, 90, 86, 87]
   Perform a t-test to determine if there is a significant difference in the mean scores between the two groups.


In [29]:
from scipy.stats import ttest_ind
A= [85, 90, 92, 88, 91]
B= [82, 88, 90, 86, 87]
H0= "the means of two groups are equal"

_,p_value= ttest_ind(A,B)
print(p_value)
if p_value < 0.05:
  print("rejecting null hypothesis")
else:
  print("failed to reject null hypothesis")

89.2
86.6
0.19023970239078333
failed to reject null hypothesis


In [ ]:
6. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
   Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
   Sales (in thousands): [25, 30, 28, 20, 26]
   Calculate the correlation coefficient between advertising expenditure and sales.


In [39]:
import pandas as pd
expen= [10, 15, 12, 8, 14]
sales= [25, 30, 28, 20, 26]

df= pd.DataFrame()
df['expen']=expen
df['sales']=sales
df.corr()['expen']['sales']

print(df['expen'].corr(df['sales']))

0.8757511375750132


In [ ]:
7. Scenario: A survey is conducted to measure the heights of a group of people. The data collected is as follows:
   [160, 170, 165, 155, 175, 180, 170]
   Calculate the standard deviation of the heights.


In [40]:
height= [160, 170, 165, 155, 175, 180, 170]
np.std(height)

7.953949089757174

In [ ]:
8. Scenario: A company wants to analyze the relationship between employee tenure and job satisfaction. The data collected is as follows:
   Employee Tenure (in years): [2, 3, 5, 4, 6, 2, 4]
   Job Satisfaction (on a scale of 1 to 10): [7, 8, 6, 9, 5, 7, 6]
   Perform a linear regression analysis to predict job satisfaction based on employee tenur


In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


In [73]:
tenure = [2, 3, 5, 4, 6, 2, 4]
job= [7, 8, 6, 9, 5, 7, 6]
df=pd.DataFrame({'tenure':tenure, 'satisfaction':job})
df.describe()
x=np.array(df['tenure']).reshape(-1,1)
y=df[['satisfaction']]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.30)
df.corr()

tenure  satisfaction
tenure        1.000000     -0.520573
satisfaction -0.520573      1.000000

In [54]:
y

satisfaction
0             7
1             8
2             6
3             9
4             5
5             7
6             6

In [74]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [75]:
reg.score(x_train,y_train)

0.018181818181818188

In [76]:
x_test=np.array(x_test).reshape(-1,1)

In [77]:
reg.score(x_test,y_test)

-5.190082644628099

In [63]:
y_pred= reg.predict(y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [64]:
y_pred

array([[4.],
       [6.],
       [5.]])

In [66]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
r2_score(y_test,y_pred)

-2.75

In [ ]:
9. Scenario: A study is conducted to compare the effectiveness of two different medications. The recovery times of the patients in each group are as follows:
   Medication A: [10, 12, 14, 11, 13]
   Medication B: [15, 17, 16, 14, 18]
   Perform an analysis of variance (ANOVA) to determine if there is a significant difference in the mean recovery times between the two medications.


In [5]:
from scipy import stats
import numpy as np

A= [10, 12, 14, 11, 13]
B= [15, 17, 16, 14, 18]
H0= "There is no significant difference"
F, p = stats.f_oneway(A,B)
if p<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

reject null hypothesis


In [ ]:
10. Scenario: A company wants to analyze customer feedback ratings on a scale of 1 to 10. The data collected is

 as follows:
    [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
    Calculate the 75th percentile of the feedback ratings.


In [6]:
A= [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
np.percentile(A,75)

8.75

In [ ]:
11. Scenario: A quality control department wants to test the weight consistency of a product. The weights of a sample of products are as follows:
    [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
    Perform a hypothesis test to determine if the mean weight differs significantly from 10 grams.


In [8]:
A=[10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
from scipy.stats import ttest_1samp
ttest,p_value=ttest_1samp(A,10)
H0="The weight does not differ from 10 grams"
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

we are accepting null hypothesis


In [ ]:
12. Scenario: A company wants to analyze the click-through rates of two different website designs. The number of clicks for each design is as follows:
    Design A: [100, 120, 110, 90, 95]
    Design B: [80, 85, 90, 95, 100]
    Perform a chi-square test to determine if there is a significant difference in the click-through rates between the two designs.


In [9]:
A= [100, 120, 110, 90, 95]
B= [80, 85, 90, 95, 100]
no_of_rows=5
no_of_columns=2
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom",ddof)
alpha = 0.05



Degree of Freedom 4


In [13]:
from scipy.stats import chi2
from scipy.stats import chi2_contingency
# Create a contingency table
observed = np.array([A, B])
H0="There is no significant differnce"
# Perform the chi-square test
chi2, p, dof, expected = chi2_contingency(observed)
if p>0.05:
  print("we are failed to reject the null hypothesis")


we are failed to reject the null hypothesis


In [ ]:
13. Scenario: A survey is conducted to measure customer satisfaction with a product on a scale of 1 to 10. The data collected is as follows:
    [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
    Calculate the 95% confidence interval for the population mean satisfaction score.


In [ ]:
A=[7, 9, 6, 8, 10, 7, 8, 9, 7, 8]


In [ ]:
14. Scenario: A company wants to analyze the effect of temperature on product performance. The data collected is as follows:
    Temperature (in degrees Celsius): [20, 22, 23, 19, 21]
    Performance (on a scale of 1 to 10): [8, 7, 9, 6, 8]
    Perform a simple linear regression to predict performance based on temperature.


In [16]:
import pandas as pd
temp=  [20, 22, 23, 19, 21]
perf= [8, 7, 9, 6, 8]
df=pd.DataFrame({'temp':temp, 'perf':perf})
df.describe()
x=np.array(df['temp']).reshape(-1,1)
y=df[['perf']]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.30)
df.corr()

temp      perf
temp  1.000000  0.693375
perf  0.693375  1.000000

In [17]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [18]:
reg.score(x_train,y_train)

0.9642857142857142

In [19]:
x_test=np.array(x_test).reshape(-1,1)

In [20]:
y_pred= reg.predict(y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [22]:
y_pred

array([[16.15194804],
       [15.09128787]])

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error as mse, r2_score
mse(y_test,y_pred)

65.96159812133745

In [24]:
reg.score(x_test,y_test)

-5.361111111111116

In [ ]:
15. Scenario: A study is conducted to compare the preferences of two groups of participants. The preferences are measured on a Likert scale from 1 to 5. The data collected is as follows:
    Group A: [4, 3, 5, 2, 4]
    Group B: [3, 2, 4, 3, 3]
    Perform a Mann-Whitney U test to determine if there is a significant difference in the median preferences between the two groups.


In [26]:
from scipy.stats import mannwhitneyu

a = [4, 3, 5, 2, 4]
b = [3, 2, 4, 3, 3]


_, p_value = mannwhitneyu(a,b, alternative='two-sided')
print("P-value:", p_value)
if p_value>0.05:
  print("failed to reject null hypothesis")

P-value: 0.380836480306712
failed to reject null hypothesis


In [ ]:
16. Scenario: A company wants to analyze the distribution of customer ages. The data collected is as follows:
    [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
    Calculate the interquartile range (IQR) of the ages.


In [27]:
A=[25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
q1= np.percentile(A,25)
q3=np.percentile(A,75)
iqr= q3-q1
print(iqr)

22.5


In [ ]:

17. Scenario: A study is conducted to compare the performance of three different machine learning algorithms. The accuracy scores for each algorithm are as follows:
    Algorithm A: [0.85, 0.80, 0.82, 0.87, 0.83]
    Algorithm B: [0.78, 0.82, 0.84, 0.80, 0.79]
    Algorithm C: [0.90, 0.88, 0.89, 0.86, 0.87]
    Perform a Kruskal-Wallis test to determine if there is a significant difference in the median accuracy scores between the algorithms.



In [29]:
from scipy.stats import kruskal

a = [0.85, 0.80, 0.82, 0.87, 0.83]
b = [0.78, 0.82, 0.84, 0.80, 0.79]
c = [0.90, 0.88, 0.89, 0.86, 0.87]


_, p_value = kruskal(a, b, c)


print("P-value:", p_value)
if p_value<0.05:
  print("reject")
else:
  print("failed to reject H0")

P-value: 0.007840333026249539
reject


In [ ]:
19. Scenario: A survey is conducted to measure the satisfaction levels of customers with a new product. The data collected is as follows:
    [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
    Calculate the standard error of the mean satisfaction score.


In [30]:
A=[7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
stdd= np.std(A)
n=len(A)
error= stdd/np.sqrt(n)
print(error)

0.28982753492378877


In [ ]:
20. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
    Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
    Sales (in thousands): [25, 30, 28, 20, 26]
    Perform a multiple regression analysis to predict sales based on advertising expenditure.


In [31]:
import pandas as pd
temp=  [10, 15, 12, 8, 14]
perf=  [25, 30, 28, 20, 26]
df=pd.DataFrame({'temp':temp, 'perf':perf})
df.describe()
x=np.array(df['temp']).reshape(-1,1)
y=df[['perf']]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.30)
df.corr()

temp      perf
temp  1.000000  0.875751
perf  0.875751  1.000000

In [32]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [33]:
x_test=np.array(x_test).reshape(-1,1)

In [34]:
y_pred= reg.predict(y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [35]:
y_pred

array([[66.30535235],
       [82.40463615]])

In [38]:
y_new= reg.predict(np.array([19]).reshape(-1,1))
y_new

array([[64.29294187]])